// Copyright (c) 2020 BitMaelum Authors
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of
// this software and associated documentation files (the "Software"), to deal in
// the Software without restriction, including without limitation the rights to
// use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
// the Software, and to permit persons to whom the Software is furnished to do so,
// subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
// FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
// COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
// IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
// CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

package container

import (
	"github.com/bitmaelum/bitmaelum-suite/internal/account"
	"github.com/bitmaelum/bitmaelum-suite/internal/apikey"
	"github.com/bitmaelum/bitmaelum-suite/internal/authkey"
	"github.com/bitmaelum/bitmaelum-suite/internal/resolver"
	"github.com/bitmaelum/bitmaelum-suite/internal/subscription"
	"github.com/bitmaelum/bitmaelum-suite/internal/ticket"
)

/*
 * Simple helpers that makes it easier to fetch services. Normally, these things should be generated by a full-fledged
 * dependency container system I guess.
 */

// GetAccountRepo will return the current account repository
func GetAccountRepo() account.Repository {
	// return Get("account").(func() account.Repository)()
	return Get("account").(account.Repository)
}

// GetAPIKeyRepo will return the current api key repository
func GetAPIKeyRepo() apikey.Repository {
	return Get("api-key").(apikey.Repository)
}

// GetAuthKeyRepo will return the current auth key repository
func GetAuthKeyRepo() authkey.Repository {
	return Get("auth-key").(authkey.Repository)
}

// GetResolveService will return the current resolver service
func GetResolveService() *resolver.Service {
	return Get("resolver").(*resolver.Service)
}

// GetSubscriptionRepo will return the current subscription repository
func GetSubscriptionRepo() subscription.Repository {
	return Get("subscription").(subscription.Repository)
}

// GetTicketRepo will return the current ticket repository
func GetTicketRepo() ticket.Repository {
	return Get("ticket").(ticket.Repository)
}
